name: Génération M3U et publication

on:
  workflow_dispatch: # permet de lancer manuellement
  schedule:
    - cron: '0 7 * * *' # tous les jours à 7h du matin (UTC)

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du repo
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Installer dépendances
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Générer le M3U
      env:
        CSV_URL: ${{ secrets.CSV_URL }}
      run: python script.py

    - name: Installer GitHub Pages Action
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: .
        # ignore le reste sauf le M3U
        # si tu veux, tu peux limiter à M3U seulement:
        # force_orphan: true

