name: Génération M3U

on:
  workflow_dispatch:   # pour lancer manuellement
  schedule:           # automatique tous les jours à 8h
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ALLDEBRID_API_KEY: ${{ secrets.ALLDEBRID_API_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script.py
        run: python script.py

      - name: Upload M3U as artifact
        uses: actions/upload-artifact@v4
        with:
          name: m3u-artifact
          path: formule2-debride.m3u
