name: Generate and Publish M3U

on:
  workflow_dispatch: # permet de lancer manuellement
  schedule:
    - cron: '0 6 * * *' # tous les jours à 6h UTC

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: pip install requests

    - name: Generate M3U
      env:
        CSV_URL: ${{ secrets.FICHIER_CSV_URL }}
        ALLDEBRID_API_KEY: ${{ secrets.ALLDEBRID_API_KEY }}
      run: python Autodebrid/script.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: Autodebrid/output
        force_orphan: true
