name: Générer et publier M3U

on:
  schedule:
    - cron: '0 7 * * *'  # tourne tous les jours à 07:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Installer dépendances
        run: pip install requests

      - name: Générer M3U
        run: python script.py

      - name: Publier M3U sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
