name: Génération et publication du M3U

on:
  workflow_dispatch:   # Permet de lancer manuellement
  schedule:            # Exécuter tous les jours à 8h
    - cron: '0 8 * * *'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      CSV_URL: ${{ secrets.CSV_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script.py
        run: python script.py

      - name: Upload M3U as artifact
        uses: actions/upload-artifact@v4
        with:
          name: m3u-artifact
          path: formule2.m3u

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          keep_files: true
          destination_dir: .
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
