name: Génération et déploiement M3U

on:
  workflow_dispatch:   # Permet de lancer manuellement
  schedule:           # Exécution automatique tous les jours à 08h
    - cron: '0 8 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      CSV_URL: ${{ secrets.CSV_URL }}
      ALLDEBRID_API_KEY: ${{ secrets.ALLDEBRID_API_KEY }}
      M3U_FILENAME: "formule2-debride.m3u"
      KEYWORD: "Course"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Vérification des fichiers
        run: ls -R Autodebrid

      - name: Génération du M3U
        run: python Autodebrid/script.py

      - name: Upload M3U as artifact
        uses: actions/upload-artifact@v4
        with:
          name: m3u-artifact
          path: Autodebrid/formule2-debride.m3u

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Autodebrid
          publish_branch: gh-pages
          keep_files: true
