name: Génération M3U

on:
  schedule:
    # Exécute tous les jours à 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  generate-m3u:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run M3U generation script
        env:
          CSV_URL: ${{ secrets.CSV_URL }}        # URL du CSV 1fichier
          ALLDEBRID_API_KEY: ${{ secrets.ALDEBRID_API_KEY }}
          FICHIER_API_KEY: ${{ secrets.FICHIER_API_KEY }}
        run: |
          python script.py

      - name: Upload M3U artifact
        uses: actions/upload-artifact@v4
        with:
          name: formule2-m3u
          path: formule2.zip
