name: Debrid M3U

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Debug repo structure
        run: |
          pwd
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script.py
        run: python script.py
        working-directory: Autodebrid

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: m3u-output
          path: Autodebrid/formule2-debride.m3u

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Autodebrid
